---

- name: Wait for qBittorrent
  ansible.builtin.wait_for:
    port: "{{ qbittorrent_port }}"
    timeout: 60

- name: Wait for qBittorrent config
  ansible.builtin.wait_for:
    path: "{{ media_stack_dir }}/config/qbittorrent/qBittorrent/qBittorrent.conf"
    timeout: 60

- name: Configure qBittorrent API key
  ansible.builtin.lineinfile:
    path: "{{ qbittorrent_config_file }}"
    regexp: '^WebUI\\APIKey='
    insertafter: '^\[Preferences\]'
    line: "WebUI\\APIKey={{ servarr_api_key }}"
  register: qbittorrent_api_key_config
  # no_log: true

- name: Configure qBittorrent password
  ansible.builtin.lineinfile:
    path: "{{ qbittorrent_config_file }}"
    regexp: '^WebUI\\Password_PBKDF2='
    insertafter: '^\[Preferences\]'
    line: 'WebUI\Password_PBKDF2={{ qbittorrent_password_hash }}'
  register: qbittorrent_password_config
  # no_log: true

- name: Configure qBittorrent settings
  ansible.builtin.lineinfile:
    path: "{{ qbittorrent_config_file }}"
    regexp: "^{{ item.key | regex_escape }}="
    insertafter: "^\\[{{ item.section }}\\]$"
    line: "{{ item.key }}={{ item.value }}"
  loop: "{{ qbittorrent_settings }}"

- name: Restart qBittorrent
  ansible.builtin.command:
    cmd: docker compose restart qbittorrent
    chdir: "{{ media_stack_dir }}"
  when: qbittorrent_config.changed

- name: Wait for qBittorrent
  ansible.builtin.wait_for:
    port: "{{ qbittorrent_webui_port }}"
    timeout: 60
  when: qbittorrent_config.changed