- name: Create Tdarr server systemd service
  ansible.builtin.copy:
    dest: /etc/systemd/system/tdarr-server.service
    mode: "0644"
    content: |
      [Unit]
      Description=Tdarr Server
      After=network.target

      [Service]
      Type=simple
      User=root
      WorkingDirectory={{ tdarr_install_dir }}
      ExecStart={{ tdarr_install_dir }}/Tdarr_Server
      Restart=always

      [Install]
      WantedBy=multi-user.target
  notify: Reload systemd
