nas_ip: "10.0.0.20"
nas_media_export: "/media"

nas_mount_fstype: nfs
nas_mount_opts: rw,_netdev,noatime,nfsvers=4

data_root: /mnt/data
torrents_root: "{{ data_root }}/torrents"
usenet_root: "{{ data_root }}/usenet"
library_root: "{{ data_root }}/media"
media_categories:
  - movies
  - tv
  - music
data_dir_mode: "0775"

media_stack_dir: /opt/media-stack

servarr_apps:
  - name: radarr
    display_name: Radarr
    image: lscr.io/linuxserver/radarr:latest
    port: 7878
    url: http://radarr:7878
    config_file: "{{ media_stack_dir }}/config/radarr/config.xml"
    api_version: v3
    root_folder_supported: true
    root_folder: "/data/media/movies"
    media_management_supported: true
    naming_config_supported: true
    naming_config_key: "renameMovies"
    prowlarr_application: true
    recyclarr_supported: true
    download_client_supported: true
    download_client_category_field: "movieCategory"
    download_client_category: "movies"

  - name: sonarr
    display_name: Sonarr
    image: lscr.io/linuxserver/sonarr:latest
    port: 8989
    url: http://sonarr:8989
    config_file: "{{ media_stack_dir }}/config/sonarr/config.xml"
    api_version: v3
    root_folder_supported: true
    root_folder: "/data/media/tv"
    media_management_supported: true
    naming_config_supported: true
    naming_config_key: "renameEpisodes"
    prowlarr_application: true
    recyclarr_supported: true
    download_client_supported: true
    download_client_category_field: "tvCategory"
    download_client_category: "tv"

  - name: lidarr
    display_name: Lidarr
    image: lscr.io/linuxserver/lidarr:latest
    port: 8686
    url: http://lidarr:8686
    config_file: "{{ media_stack_dir }}/config/lidarr/config.xml"
    api_version: v1
    root_folder_supported: false # TODO: Enable when Lidarr supports root folders in API
    root_folder: "/data/media/music"
    media_management_supported: true
    naming_config_supported: true
    naming_config_key: "renameTracks"
    prowlarr_application: true
    recyclarr_supported: false
    download_client_supported: true
    download_client_category_field: "musicCategory"
    download_client_category: "music"

  - name: prowlarr
    display_name: Prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    port: 9696
    url: http://prowlarr:9696
    config_file: "{{ media_stack_dir }}/config/prowlarr/config.xml"
    api_version: v1
    root_folder_supported: false
    media_management_supported: false
    naming_config_supported: false
    prowlarr_application: false
    recyclarr_supported: false
    download_client_supported: false

timezone: Asia/Kolkata
media_uid: 1000
media_gid: 1000

servarr_api_key: "{{ lookup('ansible.builtin.file', playbook_dir + '/../../keys/servarr_api_key') | trim }}"

qbittorrent_image: lscr.io/linuxserver/qbittorrent:latest
qbittorrent_port: 8080
qbittorrent_bittorrent_port: 6881
qbittorrent_url: http://qbittorrent:8080
qbittorrent_config_file: "{{ media_stack_dir }}/config/qbittorrent/qBittorrent/qBittorrent.conf"
qbittorrent_admin_username: admin
qbittorrent_admin_pass: >-
  {{
    lookup(
      'ansible.builtin.file',
      playbook_dir + '/../../keys/qbittorrent_admin_pass'
    ) | trim
  }}
qbittorrent_admin_pass_hash: >-
  {{
    lookup(
      'ansible.builtin.file',
      playbook_dir + '/../../keys/qbittorrent_admin_pass_hash'
    ) | trim
  }}
qbittorrent_settings:
  - section: BitTorrent
    key: Session\TorrentContentLayout
    value: Original

  - section: BitTorrent
    key: Session\DefaultSavePath
    value: "{{ torrents_root }}"

  - section: BitTorrent
    key: Session\DisableAutoTMMByDefault
    value: false
  - section: BitTorrent
    key: Session\DisableAutoTMMTriggers\CategoryChanged
    value: false
  - section: BitTorrent
    key: Session\DisableAutoTMMTriggers\CategorySavePathChanged
    value: false
  - section: BitTorrent
    key: Session\DisableAutoTMMTriggers\DefaultSavePathChanged
    value: false

  - section: BitTorrent
    key: Session\TempPathEnabled
    value: false

  - section: BitTorrent
    key: ExcludedFileNamesEnabled
    value: true
  - section: BitTorrent
    key: Session\ExcludedFileNames
    value: "*.rar, *.r[0-9]*"

  - section: BitTorrent
    key: Session\BTProtocol
    value: TCP
  - section: BitTorrent
    key: Session\Port
    value: "{{ qbittorrent_bittorrent_port }}"

  - section: BitTorrent
    key: Session\MaxConnections
    value: 300
  - section: BitTorrent
    key: Session\MaxConnectionsPerTorrent
    value: 70
  - section: BitTorrent
    key: Session\MaxUploads
    value: 15
  - section: BitTorrent
    key: Session\MaxUploadsPerTorrent
    value: 4

  - section: BitTorrent
    key: Session\GlobalDLSpeedLimit
    value: 28000
  - section: BitTorrent
    key: Session\GlobalUPSpeedLimit
    value: 3000

  - section: BitTorrent
    key: Session\IgnoreLimitsOnLAN
    value: false
  - section: BitTorrent
    key: Session\IncludeOverheadInLimits
    value: false
  - section: BitTorrent
    key: Session\uTPRateLimited
    value: true

  - section: BitTorrent
    key: Session\DHTEnabled
    value: true
  - section: BitTorrent
    key: Session\PeXEnabled
    value: true
  - section: BitTorrent
    key: Session\LSDEnabled
    value: true
  - section: BitTorrent
    key: Session\Encryption
    value: 0
  - section: BitTorrent
    key: Session\AnonymousModeEnabled
    value: false

  - section: BitTorrent
    key: Session\GlobalMaxInactiveSeedingMinutes
    value: -1
  - section: BitTorrent
    key: Session\GlobalMaxRatio
    value: -1
  - section: BitTorrent
    key: Session\GlobalMaxSeedingMinutes
    value: -1

  - section: Network
    key: PortForwardingEnabled
    value: false

  - section: Core
    key: AutoDeleteAddedTorrentFile
    value: IfAdded



tdarr_install_dir: "/opt/tdarr"
tdarr_node_name: "{{ inventory_hostname }}"
tdarr_server_ip: "10.0.5.1"
tdarr_server_port: 8266
tdarr_upgrade: false
