- name: Verify mount exists
  command: mountpoint -q /mnt/media
  register: mount_check
  failed_when: mount_check.rc != 0

- name: Check Jellyfin port
  ansible.builtin.wait_for:
    port: 8096
    host: "{{ ansible_host }}"
    timeout: 30

# - name: Check Tdarr node port
#   ansible.builtin.wait_for:
#     port: 8267
#     host: "{{ ansible_host }}"
#     timeout: 30
