nas_ip: "10.0.1.10"
nas_media_export: "/mnt/tank/media"

tdarr_version: "2.00.20"
tdarr_install_dir: "/opt/tdarr"
tdarr_server_port: 8266
tdarr_web_port: 8265
tdarr_upgrade: false

media_mgmt_servarr_api_key: "{{ lookup('ansible.builtin.file', playbook_dir + '/../../keys/servarr_api_key') | trim }}"

recyclarr_enabled: true
recyclarr_version: latest
recyclarr_config_dir: /etc/recyclarr
recyclarr_sonarr_url: http://localhost:8989
recyclarr_radarr_url: http://localhost:7878
recyclarr_api_key: "{{ media_mgmt_servarr_api_key }}"