---
all:
  vars:
    ansible_user: iac
    ansible_become: true
    ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new"

  children:

    iac_controller:
      hosts:
        prod-iac-01:

    ci_runners:
      hosts:
        prod-ci-runner-01:

    monitoring:
      hosts:
        prod-monitoring-01:

    databases:
      hosts:
        prod-db-01:

    media:
      hosts:
        prod-media-01:

    docs:
      hosts:
        prod-docs-01:
